### ISSUE TITLE
Feature request: use of django channels instead of celery?

### ISSUE THREAD

**Issue by dkdndes** [vitorfs/colossus#21]
Is it possible to use colossus with channels, and this way use Django Foundation supported core features, only?

**Comment by vitorfs** [comment]
Django Channels and Celery tackle different problems. Celery is currently being used to handle heavy duty tasks outside the request/response cycle. For example sending bulk emails, which can take a few minutes to complete. It's also used to run tasks in the background to clean up the list when there is available resources on the server. Or to update Geolocation data on the subscribers. 

Django Channels could be added to handle the notification system for example, but it's not on my roadmap at the moment. It would be just nice to have, but very little benefit.
