### ISSUE TITLE
500 Server Error when trying to import contacts through paste on Heroku

### ISSUE THREAD

**Issue by alexsonnay** [vitorfs/colossus#24]
![image](https://user-images.githubusercontent.com/28756458/46033606-e7eb8c00-c0fe-11e8-8d47-4388b20cd73f.png)

**Comment by vitorfs** [comment]
Can you provide some further info from the logs please? It will help investigating the issue

**Comment by alexsonnay** [comment]
I don't have the log anymore as I have removed Heroku but I will try on my local server.

Other question : is it possible to use it with AWS SMTP ? I don't see where in the settings you can set the access and private keys. 

Thx

**Comment by vitorfs** [comment]
Yep, I'm currently using it for my newsletter:

https://colossus.simpleisbetterthancomplex.com/newsletter/

I know that AWS SES needs domain verification or whitelisting while in "test" mode

But regardless I will try to debug and see if anything is wrong

**Comment by alexsonnay** [comment]
Yes exactly. My domains and email addresses are verified. I use AWS with PHPMailer and it works fine. So I'm wondering what did I do wrong in Colossus settings...

**Comment by alexsonnay** [comment]
Yes exactly. My domains and email addresses are verified. I use AWS with PHPMailer and it works fine. So I'm wondering what I did wrong in Colossus settings... If you have any idea ? Could you send me a capture of your settings (blurring the credentials of course) ?

**Comment by vitorfs** [comment]
My settings file is exactly the one in the repository at the moment, you can see the email config here:

https://github.com/vitorfs/colossus/blob/master/colossus/settings.py#L149

All the values are modified using environment variables, or a `.env` file in project root directory (same directory as `manage.py` file):

**.env**

```
SERVER_EMAIL=colossus@simpleisbetterthancomplex.com
DEFAULT_FROM_EMAIL=Vitor Freitas <vitor@simpleisbetterthancomplex.com>
EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
EMAIL_HOST=smtp.mailgun.org
EMAIL_HOST_USER=myusername
EMAIL_HOST_PASSWORD=mypassword
```

**Comment by alexsonnay** [comment]
I edited the settings.py file directly maybe that's why then.

I don't have any .env file though while local server running.

**Comment by alexsonnay** [comment]
I edited the settings.py file directly maybe that's why then. 

This is the full content of the .env file ? I tried creating one but it doesn't seem to take it in account.

**Comment by alexsonnay** [comment]
```

Request Method: | POST
-- | --
http://127.0.0.1:8000/lists/2/subscribers/import/paste/
2.1
IntegrityError
NOT NULL constraint failed: colossus_subscribers.domain_id
/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py in execute, line 296
/usr/local/opt/python/bin/python3.7
3.7.0
['/Users/stan/Desktop/Colossus',  '/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python37.zip',  '/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7',  '/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload',  '/usr/local/lib/python3.7/site-packages',  '/Users/stan/Desktop/Colossus']
Wed, 26 Sep 2018 18:37:09 +0000


```
