### ISSUE TITLE
'NoneType' object has no attribute 'tags'

### ISSUE THREAD

**Issue by NayabKhan2019Mar03** [vitorfs/colossus#31]
I am getting the attached when i am adding  PRECIPITANTS ,please help sir
![error](https://user-images.githubusercontent.com/48717648/56460421-0af1cc00-63c0-11e9-8ec7-03163ba510be.png)

**Comment by NayabKhan2019Mar03** [comment]
getting in campaigns/forms.py at line number 76

"colossus\apps\campaigns\forms.py", line 76, in __init__
    self.fields['tag'].queryset = self.instance.mailing_list.tags.order_by('name')"
AttributeError: 'NoneType' object has no attribute 'tags'

**Comment by vitorfs** [comment]
@NayabKhan2019Mar03 Fixed with PR https://github.com/vitorfs/colossus/pull/32
